{% set name = "fasthx" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fasthx-{{ version }}.tar.gz
  sha256: 553f2e78b36d85b66d7cd7612c52d1131fb6fe5cb65d7f5d5908e7bcec63a951

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10.0,<4.0.0
    - poetry-core
    - pip
  run:
    - python >=3.10.0,<4.0.0
    - fastapi >=0.100.0
    - typing-extensions >=4.5.0

test:
  imports:
    - fasthx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/volfpeter/fasthx
  doc_url: https://volfpeter.github.io/fasthx/
  summary: FastAPI data APIs with HTMX support.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
