{% set python_min = python_min|default("0.1a0") %}
{% set name = "fasthx" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fasthx-{{ version }}.tar.gz
  sha256: 76fb80dc61b24555111d212a468f04cde448342b7654e51ac0eed84231272eb0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - fastapi >=0.100.0
    - typing_extensions >=4.5.0

test:
  imports:
    - fasthx
  commands:
    - pip check
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/volfpeter/fasthx
  doc_url: https://volfpeter.github.io/fasthx/
  summary: FastAPI data APIs with HTMX support.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
