{% set name = "fasthx" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fasthx-{{ version }}.tar.gz
  sha256: c528bada92906d32941277f82175823cb154da291c8b185a5afaa4db14f60982

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10.0,<4.0.0
    - poetry-core
    - pip
  run:
    - python >=3.10.0,<4.0.0
    - fastapi >=0.100.0

test:
  imports:
    - fasthx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/volfpeter/fasthx
  doc_url: https://volfpeter.github.io/fasthx/
  summary: FastAPI data APIs with HTMX support.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
