schema_version: 1

context:
  name: fasthx
  version: "3.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fasthx-${{ version }}.tar.gz
  sha256: 8826004329d2b3a557963e39ea73baf0a311c63628c411723b76d4f0dfef53ae

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - python >=${{ python_min }}
    - fastapi >=0.100.0

tests:
  - python:
      imports:
        - fasthx
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: FastAPI data APIs with HTMX support.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/volfpeter/fasthx
  documentation: https://volfpeter.github.io/fasthx/

extra:
  recipe-maintainers:
    - thewchan
