schema_version: 1

context:
  name: fasthx
  version: "3.2.1"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fasthx-${{ version }}.tar.gz
  sha256: 6f77fffaad8b7e02a5a57f363cd6caea9d057ce9f97ba86eab95c3e4fee72f9f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - python >=${{ python_min }}
    - fastapi >=0.135.0

tests:
  - python:
      imports:
        - fasthx
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: FastAPI data APIs with HTMX support.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/volfpeter/fasthx
  documentation: https://volfpeter.github.io/fasthx/

extra:
  recipe-maintainers:
    - davidbrochart
    - thewchan
