schema_version: 1

context:
  name: fasthx
  version: "3.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fasthx-${{ version }}.tar.gz
  sha256: a164b8b0f6ab1c0b62a82266e385b2fd6ff34e0128a8677e2f1ca9e7556a3a68

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - fastapi >=0.100.0

tests:
  - python:
      imports:
        - fasthx
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: FastAPI data APIs with HTMX support.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/volfpeter/fasthx
  documentation: https://volfpeter.github.io/fasthx/

extra:
  recipe-maintainers:
    - thewchan
